name: bank_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.6.8
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  logger: ^2.2.0
  hive: ^2.2.3
  dio: ^5.4.2+1
  injectable: ^2.4.1
  cached_network_image: ^3.3.1
  lottie: ^3.1.0
  google_fonts: any
  provider: ^6.1.2
  local_auth: ^2.3.0
  mask_text_input_formatter: ^2.9.0
  flutter_svg: any
  pinput: ^4.0.0
  image_picker: ^1.1.2
  cloud_firestore: ^5.3.0
  table_calendar: ^3.1.2
  fl_chart: ^0.69.0
  firebase_core: ^3.4.0
  animations: ^2.0.11
#  emoji_picker_flutter: ^3.0.0
  flutter_vector_icons: ^2.0.0
  firebase_storage: ^12.2.0
  image_cropper: ^8.0.2
  flutter_screen_lock: ^9.1.0
  jwt_decoder: ^2.0.1
  html: ^0.15.0
  pretty_dio_logger: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.9
  freezed: ^2.5.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/


flutter_gen:
  output: lib/data/gen
  integrations:
    flutter_svg: true
